### ISSUE TITLE
Public notices screen: canceled throws in 'undefined' text

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/notice-signage#9]
On the public notices screen on the first floor of City Hall, when an event is cancelled the screen shows the words 'undefinedcanceled'. The screen should only show 'canceled'.

Doesn't appear to be an issues on boston.gov website

![ec95cb2e-ee2f-11e6-85a8-b2336f1d83e6](https://cloud.githubusercontent.com/assets/20731897/22788508/005d4eec-eeae-11e6-9024-86835a9bd036.jpg)

**Comment by jfh01** [comment]
In case it helps diagnose, this was happening to most (but not all) of the entries on the board today:
 
![img_3032](https://cloud.githubusercontent.com/assets/578157/23904610/df117a46-089e-11e7-917d-0883ed9368a0.jpg)

**Comment by matthewcrist** [comment]
Took a while to get a cancelled notice on the sign, but this is fixed.

![image uploaded from ios](https://cloud.githubusercontent.com/assets/9234/25752040/14d416b6-3185-11e7-89b5-c602ffc1132a.jpg)
